#!/usr/local/bin/python3

import feedparser

url= "https://arkiv.radio24syv.dk/rss"
feed = feedparser.parse(url)

def get_enclosureurl():
  return(post.links[0].href)

def get_enclusoretype():
  return()

def get_enclosurelength():
  return(post.links[0].length)

def get_title():
  return(post.title)

def get_link():
  return(post.link)

def get_image():
  return(post.image.href)

def get_guid():
  return(post.guid.split("/")[4])

def get_pubdate():
  date = "%d/%02d/%02d" % (post.published_parsed.tm_year,\
    post.published_parsed.tm_mon, \
    post.published_parsed.tm_mday)
  return(date)

def get_summary():
  return(post.summary)

def get_itunesauthor():
  return()

def get_duration():
  return(post.itunes_duration)

def get_itunesimage():
  return()


for post in feed.entries:
  print("----------------")
  print("Image: " + get_image())
  print("GUID: " + get_guid())
  print("Pubdate: " + get_pubdate())
  print("Title: " + get_title())
  print("Link: " + get_link())
  print("Duration: " + get_duration())
  print("Summary: " + get_summary())
  print("Enclosureurl: " + get_enclosureurl())
  print("Enclosurelength: " + get_enclosurelength())
