#!/usr/local/bin/python3

import feedparser
import sqlite3
import json

debug = 1;
page = "1";
url = 'https://arkiv.radio24syv.dk/rss?p=' + page
feed = feedparser.parse(url)
db = sqlite3.connect('arkiv24syv.db')

if (debug):
  print ("Page is: " + page);
  print ("url is: " + url);

cursor = db.cursor()
cursor.execute('''CREATE TABLE IF NOT EXISTS items (
  x INTEGER PRIMARY KEY ASC,
  entirepost,
  contenturl,
  filesize,
  imagelink,
  title,
  link,
  description,
  guid,
  pubdate,
  duration,
  downloaded,
  imagedownloaded,
  sha256sum
);''')
db.commit

def get_enclosureurl():
  string = post.links[0].href
  string = string.strip('?source=podcast')
  return(string)

def get_enclosurelength():
  return(post.links[0].length)

def get_title():
  return(post.title)

def get_link():
  return(post.link)

def get_image():
  return(post.image.href)

def get_guid():
  return(post.guid.split("/")[4])

def get_pubdate():
  date = "%d/%02d/%02d" % (post.published_parsed.tm_year,\
    post.published_parsed.tm_mon, \
    post.published_parsed.tm_mday)
  return(date)

def get_summary():
  return(post.summary)

def get_duration():
  return(post.itunes_duration)

for post in feed.entries:
  cursor.execute('''SELECT count(*) FROM items WHERE guid = ?''', (get_guid(),))
  if cursor.fetchone()[0]==0:
    if (debug):
      print("Inserting " + get_guid())
    cursor.execute('''INSERT INTO items(entirepost, contenturl, duration, filesize, pubdate, guid, imagelink, downloaded) VALUES(?,?,?,?,?,?,?,?)''', (json.dumps(post), get_enclosureurl(), get_duration(), get_enclosurelength(), get_pubdate(), get_guid(), get_image(), '0'))
  else:
    if (debug):
      print("Skipped " + get_guid())

db.commit()
db.close()

